// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.http;

import com.asaas.apisdk.exceptions.ApiError;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import okhttp3.Response;
import org.openapitools.jackson.nullable.JsonNullableModule;

public final class ModelConverter {

  private static final ObjectMapper mapper = new ObjectMapper();

  static {
    mapper.setSerializationInclusion(JsonInclude.Include.NON_ABSENT);
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    mapper.configure(DeserializationFeature.FAIL_ON_INVALID_SUBTYPE, false);
    mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
    mapper.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
    mapper.enable(SerializationFeature.WRITE_ENUMS_USING_TO_STRING);
    mapper.enable(DeserializationFeature.READ_ENUMS_USING_TO_STRING);
    mapper.enable(DeserializationFeature.USE_LONG_FOR_INTS);
    mapper.registerModule(new JsonNullableModule());
  }

  private ModelConverter() {}

  public static <T> T convert(final Response response, final Class<T> clazz) {
    try {
      return mapper.readValue(readBodyAsString(response), clazz);
    } catch (Exception e) {
      throw buildConversionApiError(response, String.format("deserialize response body to %s", clazz.getSimpleName()), e);
    }
  }

  public static <T> T convert(final String response, final Class<T> clazz) {
    try {
      return mapper.readValue(response, clazz);
    } catch (Exception e) {
      e.printStackTrace();
      return null;
    }
  }

  public static <T> T convert(Response response, TypeReference<T> typeReference) {
    try {
      return mapper.readValue(readBodyAsString(response), typeReference);
    } catch (Exception e) {
      throw buildConversionApiError(response, "deserialize response body", e);
    }
  }

  public static <T> T convert(String response, TypeReference<T> typeReference) {
    try {
      return mapper.readValue(response, typeReference);
    } catch (Exception e) {
      e.printStackTrace();
      return null;
    }
  }

  public static String readString(Response response) {
    try {
      return readBodyAsString(response);
    } catch (Exception e) {
      throw buildConversionApiError(response, "read response body as string", e);
    }
  }

  public static byte[] readBytes(Response response) {
    try {
      if (response.body() == null) {
        throw new IllegalStateException("Response body is empty");
      }
      return response.body().bytes();
    } catch (Exception e) {
      throw buildConversionApiError(response, "read response body as bytes", e);
    }
  }

  public static String modelToJson(final Object model) {
    try {
      return mapper.writeValueAsString(model);
    } catch (Exception e) {
      e.printStackTrace();
      return null;
    }
  }

  private static String readBodyAsString(Response response) throws Exception {
    if (response.body() == null) {
      throw new IllegalStateException("Response body is empty");
    }

    return response.body().string();
  }

  private static ApiError buildConversionApiError(Response response, String action, Exception cause) {
    int status = response != null ? response.code() : 0;
    String url = response != null && response.request() != null ? response.request().url().toString() : "unknown";

    String message = String.format("Failed to %s (status: %d, url: %s)", action, status, url);
    // TODO: Consider a dedicated response-conversion exception type for malformed 2xx payloads.
    ApiError error = new ApiError(message, status, response);
    error.initCause(cause);
    return error;
  }
}
